arch: 
  - amd64
  
os: linux
dist: focal
service: docker
language: node_js
node_js: 12

before_script: npm install -g typescript

script:
  - git clone https://github.com/che-incubator/setup-minikube-action.git
  - cd setup-minikube-action
  - tsc
  - ls -l
  - node lib/index.js
