arch: 
  - amd64
  
os: linux
dist: focal
service: docker
language: node_js
node_js: 12

script:
  - npm install -g typescript
  - git clone https://github.com/che-incubator/setup-minikube-action.git
  - cd setup-minikube-action
  - npm install
  - export RUNNER_TEMP=/tmp
  - env 'INPUT_MINIKUBE-VERSION=v1.18.1' node lib/index.js
