arch: 
  - amd64
  
os: linux
dist: focal
service: docker
language: node_js
node_js: 12

script:
  - npm install -g typescript
  - git clone https://github.com/che-incubator/setup-minikube-action.git
  - cd setup-minikube-action
  - npm install
  - tsc
  - ls -l lib/
  - sudo -E node lib/index.js
