arch: 
  - amd64
  - ppc64le
  - s390x
  
os: linux
dist: focal
service: docker

before_script: chmod +x .travis/*.sh

script:
  - free -h
  - df -h
  - ./.travis/setup-minikube.sh
  - kubectl get nodes
