arch: 
  - amd64
  
os: linux
dist: focal
service: docker
language: node_js
node_js: 12

script:
  - npm install -g typescript
  - export RUNNER_TEMP=/tmp
  - export SKIP_TEST=true
  - export SKIP_FORMAT=true
  - git clone https://github.com/che-incubator/setup-minikube-action.git
  - cd setup-minikube-action
  - npm install
  - env 'INPUT_MINIKUBE-VERSION=v1.18.1' node lib/index.js
  - cd ..
  - git clone https://github.com/che-incubator/che-deploy-action.git
  - cd che-deploy-action
  - npm install
  - env 'INPUT_CHECTL-CHANNEL=next' node lib/index.js
  - cd ..
